steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/deft-cove-284019/sped-backend-image', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/deft-cove-284019/sped-backend-image']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'sped-cloud-backend', '--image', 'gcr.io/deft-cove-284019/sped-backend-image:$COMMIT_SHA', '--region', 'us-central1', '--platform', 'managed']
images:
- 'gcr.io/deft-cove-284019/sped-backend-image:$COMMIT_SHA'